In [5]:
%pwd

'/Users/aoamacsplace/Documents/DS_Projects/transaction_monitoring/research'

In [6]:
import os

In [7]:
os.chdir("../")

In [8]:
%pwd

'/Users/aoamacsplace/Documents/DS_Projects/transaction_monitoring'

In [9]:
import pandas as pd
from transaction_monitoring.config.configuration import Configuration

# Load configuration
config = Configuration()

# Load the saved raw data
data_path = f"{config.data_ingestion.raw_data_dir}/raw_data.csv"

# Read and display the data
df = pd.read_csv(data_path)
df.head()  # Display first few rows

2025-03-15 14:56:56,355 - INFO - üîç Attempting to load configuration from: config/config.yaml
2025-03-15 14:56:56,358 - INFO - ‚úÖ Configuration loaded successfully.
2025-03-15 14:56:56,358 - INFO - üìÇ Data Ingestion Config - Data Path: data/input.csv, Raw Data Dir: data/raw

,ssn,cc_num,first,last,gender,street,city,state,zip,lat,...,customer_avg_amount_7_day,customer_avg_amount_30_day,merchant_num_trans_1_day,merchant_num_trans_7_day,merchant_num_trans_30_day,merchant_risk_1_day,merchant_risk_7_day,merchant_risk_30_day,merchant_risk_90_day,age
0,305-46-8995,6533797437394335,Elizabeth,Rivera,0,44633 Gray Highway Apt. 612,Bradenton,FL,34210,27.4544,...,41.49,55.77,891.33,87428.94,400451.39,2,11,12,24,79
1,106-82-9631,4514372317296618,Brandon,Carrillo,1,79880 Hicks Summit Apt. 271,Appleton,WI,54913,44.3456,...,35.40,17.95,272.58,74962.83,830852.24,6,6,11,28,48
2,307-57-8285,4926911616466638,Cathy,Jordan,0,829 Gordon Row,Tucson,AZ,85746,32.1422,...,34.11,60.11,3831.12,8049.08,983290.38,7,9,9,47,38
3,033-10-2894,213148280092057,David,Cruz,1,5686 George Camp,Interlaken,NY,14847,42.6165,...,5.58,39.19,2777.36,36374.12,664644.05,4,6,16,44,62
4,097-89-8606,3506323654018141,Dylan,Jackson,1,02435 Heidi Inlet Suite 651,Oklahoma City,OK,73107,35.4874,...,50.98,45.62,1347.50,84760.22,284588.94,4,14,19,24,37